language:
    - cpp
            
before_install:
    - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "groypyspoopyboi"
    token:
      secure: "S7LSQFGKAUo9WnSmryweF6ai1DZnlU5nDVLgpPKBKxtOPbvJCFRmyNSUAd3G1zHafsU2muX8g2Dx2i83FiUToZZTVDz9hIW0cxCqDTOsCS4b5TTOLf8fFjEDQolJIQStNzQalv4JlXR/CIqsLbS00132jfF/J3B+uHLb1rJMAhY3yZRuPsebBtWFOZSV7OMqHwo/NqcvVDTxQaZT+w70G+4LFJScLdyHHSFDHWDz7BSQ3tj3m22Zg1bO9SI2ogGuiSOgzE5OqXNNqs/KUYuiz7HAhi5p81jnVcqmMithg/Q75tKfZJSrbshixjMsNxcUgSpYXTIe3f1SApJmfUlykPf//V8JW8H+3BX1T28GGiKaoVL5VrLOIjcpQtdr0n+kMdvaGi2LbggfkMdb5L4DYfzUWMe/iE4Nndfh1XDUGfdfF6J6EJgEHiK0EJBtNnURd2W8G9j/9znk0+Srv+I3tg2DoChzU4TQojal1SHcAiBy/VFWjdXbeZYxtGYKy/TtpbwP1Zmj7XYFmAb8qk9/LgWRLZhPVypN/WHZRFPT52mAZhCgblNw9ncodY048tcpKaq+F5zODZrPWDpeQ2odcCMXbFyw5Xl9YGdsbfFOZgY031IeYvPU8eoUDLOjHHjGarA1Mm9SY5Pb2N7YtuzMuee+rfdl3w9U5wOAVvr8dgU="

script:
    - qmake 
    - make
    - ./tests/tests
    
after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
    email: false 